name: deep-learning
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python
    - numpy==1.13.3
    - matplotlib
    - jupyter
    - opencv3
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - ffmpeg
    - imageio=2.1.2
    - pyqt=4.11.4
    - pip:
        - moviepy

        # The following line is for GPU-based machines. Uncomment it on GPU machines
        #- tensorflow-gpu==1.6.0

        # Uncomment the following line to use non-GPU tensorflow
        - tensorflow==1.6.0

        - tensorboard==1.6.0
        - keras==2.1.4
        - jupyterthemes
        - keras-vis
        - protobuf
        - lxml
        - Cython
